### ISSUE TITLE
Pull request are getting deployed by travis-ci

### ISSUE THREAD

**Issue by alexdeleon** [bq/corbel#2]
Currently, because of the maven deploy in the .travis.yml,  every pull request is getting deployed to the repo... this will cause problems.

My suggestions
----------------------
1. Remove deploy from travis , and do this from the internal jenkins.
2. Use a script in travis which will only do a maven deploy if the branch is master.

**Comment by yebenes** [comment]
Good point! :+1: 

It makes sense that travis-ci just run the unit tests.

Thank you very much for writing this issue! :)
